# Generated by Django 4.2.13 on 2024-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='contnt',
            new_name='content',
        ),
    ]
